spring.application.name=notification-service

server.port=8080

spring.kafka.bootstrap-servers=kafka:9092



spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.mvc.async.request-timeout=-1

server.tomcat.keep-alive-timeout=600000
server.tomcat.connection-timeout=600000
